/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LiferayStore;

import java.io.*;
import java.util.Arrays;
import java.util.stream.Stream;

public class App {

    private static Basket readInput() throws IOException {

        Basket basket = new Basket();

        try (
                FileReader fileReader = new FileReader("src/main/resources/Input3.txt");
                BufferedReader bufferedReader = new BufferedReader(fileReader);
                Stream<String> lines = bufferedReader.lines()
        ) {
            lines.forEach(line -> {
                String[] words = line.split(" ");
                int quantity = Integer.parseInt(words[0]);
                double price = Double.parseDouble(words[words.length - 1]);
                String name = String.join(" ", Arrays.copyOfRange(words, 1, words.length - 2));
                basket.addItem(quantity, name, price);
            });
        }

        return basket;
    }

    public static void main(String[] args) throws IOException {

        Basket basket = readInput();
        Basket.printOutput(basket);
    }
}
